# Generated by Django 5.2.4 on 2025-07-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Planname')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='Plantyp')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monatspreis (€)')),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jahrspreis (€)')),
                ('max_installations', models.PositiveIntegerField(verbose_name='Max. Anlagen')),
                ('max_users', models.PositiveIntegerField(verbose_name='Max. Benutzer')),
                ('max_storage_gb', models.PositiveIntegerField(verbose_name='Max. Speicher (GB)')),
                ('features', models.JSONField(default=list, verbose_name='Features')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Abonnement-Plan',
                'verbose_name_plural': 'Abonnement-Pläne',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('cancelled', 'Gekündigt'), ('expired', 'Abgelaufen'), ('pending', 'Ausstehend')], default='pending', max_length=20, verbose_name='Status')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monatlich'), ('yearly', 'Jährlich')], default='monthly', max_length=20, verbose_name='Abrechnungszyklus')),
                ('start_date', models.DateTimeField(verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(verbose_name='Enddatum')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Zahlungsmethode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.subscriptionplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen'), ('refunded', 'Erstattet')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Kreditkarte'), ('bank_transfer', 'Banküberweisung'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20, verbose_name='Zahlungsmethode')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaktions-ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Zahlungsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.subscription', verbose_name='Abonnement')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
