# Generated by Django 5.2.4 on 2025-07-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=20, unique=True, verbose_name='Kundennummer')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Unternehmen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.CreateModel(
            name='PVInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Anlagennummer')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Anlagengröße (kWp)')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Standort')),
                ('module_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modultyp')),
                ('module_manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modulhersteller')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='installation_profiles/', verbose_name='Profilbild der Anlage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gesamtleistung (kW)')),
                ('number_of_modules', models.PositiveIntegerField(blank=True, null=True, verbose_name='Anzahl der Module')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('maintenance', 'Wartung'), ('error', 'Fehler'), ('offline', 'Offline')], default='active', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch'), ('critical', 'Kritisch')], default='medium', max_length=20, verbose_name='Priorität')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Inbetriebnahmedatum')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Garantieablauf')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('inverter_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wechselrichter-Typ')),
                ('inverter_manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wechselrichter-Hersteller')),
                ('inverter_serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wechselrichter-Seriennummer')),
                ('api_endpoint', models.URLField(blank=True, null=True, verbose_name='API-Endpunkt für Wechselrichter-Daten')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API-Schlüssel')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ansprechpartner')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kontakt-Telefon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kontakt-E-Mail')),
                ('general_notes', models.TextField(blank=True, verbose_name='Allgemeine Notizen')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (kommagetrennt)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='accounts.company', verbose_name='Firma/Mandant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installations', to=settings.AUTH_USER_MODEL, verbose_name='Angelegt von')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='installations.customer', verbose_name='Betreiber/Kunde')),
            ],
            options={
                'verbose_name': 'PV-Anlage',
                'verbose_name_plural': 'PV-Anlagen',
            },
        ),
        migrations.CreateModel(
            name='InstallationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('note_type', models.CharField(choices=[('general', 'Allgemein'), ('maintenance', 'Wartung'), ('issue', 'Problem'), ('improvement', 'Verbesserung'), ('contact', 'Kontakt'), ('other', 'Sonstiges')], default='general', max_length=20, verbose_name='Notiztyp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('is_important', models.BooleanField(default=False, verbose_name='Wichtig')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='installations.pvinstallation', verbose_name='Anlage')),
            ],
            options={
                'verbose_name': 'Anlagennotiz',
                'verbose_name_plural': 'Anlagennotizen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routinewartung'), ('repair', 'Reparatur'), ('inspection', 'Inspektion'), ('cleaning', 'Reinigung'), ('upgrade', 'Upgrade'), ('emergency', 'Notfall'), ('other', 'Sonstiges')], max_length=20, verbose_name='Wartungstyp')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('scheduled_date', models.DateField(verbose_name='Geplantes Datum')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('status', models.CharField(choices=[('scheduled', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen'), ('overdue', 'Überfällig')], default='scheduled', max_length=20, verbose_name='Status')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kosten')),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='Wartungsnotizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work', to=settings.AUTH_USER_MODEL, verbose_name='Techniker')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='installations.pvinstallation', verbose_name='Anlage')),
            ],
            options={
                'verbose_name': 'Wartungsprotokoll',
                'verbose_name_plural': 'Wartungsprotokolle',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InstallationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='installation_images/', verbose_name='Bild')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Beschriftung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='installations.pvinstallation', verbose_name='Anlage')),
            ],
            options={
                'verbose_name': 'Anlagenbild',
                'verbose_name_plural': 'Anlagenbilder',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='installation_documents/', verbose_name='Dokument')),
                ('document_type', models.CharField(choices=[('manual', 'Handbuch'), ('warranty', 'Garantie'), ('certificate', 'Zertifikat'), ('maintenance', 'Wartungsprotokoll'), ('invoice', 'Rechnung'), ('contract', 'Vertrag'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Dokumenttyp')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Beschreibung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_documents', to='accounts.company', verbose_name='Firma/Mandant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='installations.pvinstallation', verbose_name='Anlage')),
            ],
            options={
                'verbose_name': 'Anlagendokument',
                'verbose_name_plural': 'Anlagendokumente',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallationDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Zeitstempel')),
                ('power_output', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Leistung (kW)')),
                ('energy_today', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Energie heute (kWh)')),
                ('energy_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gesamtenergie (kWh)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatur (°C)')),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Spannung (V)')),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Strom (A)')),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Wirkungsgrad (%)')),
                ('status_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status-Code')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Rohdaten')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='installations.pvinstallation', verbose_name='Anlage')),
            ],
            options={
                'verbose_name': 'Datenpunkt',
                'verbose_name_plural': 'Datenpunkte',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['installation', 'timestamp'], name='installatio_install_fec352_idx')],
            },
        ),
    ]
